{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "database.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{- if .Values.database.password }}
  database-password: {{ .Values.database.password | b64enc | quote }}
{{- else }}
  database-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
{{- if .Values.database.rootPassword }}
  database-root-password: {{ .Values.database.rootPassword | b64enc | quote }}
{{- else }}
  database-root-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
{{- if .Values.database.user }}
{{- else -}}
{{ $username := printf "passbolt-%s" (randAlphaNum 5) }}
  database-user: {{ $username | b64enc | quote }}
{{- end }}
{{- end -}}