{{- if and .Values.passbolt.tls.enabled (eq .Values.passbolt.ingress.letsEncrypt.enabled false) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "passbolt.fullname" . }}-cert
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{- $path := printf "certs/*" .Release.Name }}
{{ (.Files.Glob $path).AsConfig | indent 2 }}
{{- end -}}