apiVersion: v1
kind: Service
metadata:
  name: {{ template "passbolt.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.passbolt.service.type }}
  ports:
{{- if .Values.passbolt.tls.enabled }}
    - port: 443
      targetPort: {{ .Values.passbolt.service.port | default "443" }}
{{- else }}
    - port: 80
      targetPort: {{ .Values.passbolt.service.port | default "80" }}
{{- end }}
      protocol: TCP
  selector:
    app: {{ template "passbolt.fullname" . }}