{{- if .Values.passbolt.config.license.enabled  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "passbolt.fullname" . }}-license
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{- $path := printf "passboltlicense/*" .Release.Name }}
{{ (.Files.Glob $path).AsConfig | indent 2 }}
{{- end -}}